// Code generated by go-swagger; DO NOT EDIT.

// Package restapi IAM API
//
//  Move programming from the user to the machine.
//  Schemes:
//    https
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/x-www-form-urlencoded
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
